audit_header: false
title: Central Florida Real Estate Video Blog with Tammie Pickard
description: >-
  Our mission at Team Central Florida is to be your best resource for Central
  Florida real estate advice. Whether you are a buyer, seller, or investor, our
  team of professionals can answer any questions you might have about real
  estate. If you are looking to buy or sell a home, you can get all the
  information and the latest updates, tips, and tricks from The Team Central
  Florida, your professional Central Florida Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Tammie Pickard
  title:
  license_number:
  about_markdown: >-
    A Florida Resident for over 50 years, Tammie Pickard began her real estate
    career in 2000 after investing in and managing over 20 investment
    properties. When her husband was diagnosed as a terminal patient, Tammie
    chose to turn her passion into her career.


    In 2000, Tammie was recognized as “Rookie of the Year” and went on to win
    several “President’s Awards”. She was a member of the “100 Club” year after
    year.


    With her background in business and residential, Tammie specialized in
    Residential and Commercial Real Estate. Tammie has extensive knowledge of
    1031 Exchanges and Investment Properties.
  brand: Team Central Florida
  brokerage: Keller Williams
  market: Central Florida
  address: '4152 Lakewood Ranch Blvd. Lakewood Ranch, FL 34211'
  phone: 941-219-9300
  phone_type:
  phone2:
  phone2_type:
  email: tammiepickard@kw.com
  url: 'http://teamcentralflorida.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.teamcentralflorida.com/what-s-your-home-worth'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.teamcentralflorida.com/listings-search/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Central Florida Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'https://www.teamcentralflorida.com/what-s-your-home-worth'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Central Florida Home?
    CTA_text2: Search the entire MLS for your Central Florida home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.teamcentralflorida.com/listings-search/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Team-Central-Florida-1700203313618211/'
  linkedin_url:
  youtube_url: 'http://www.youtube.com/UCG04Xm5q1Fp1rnAigVsh8Cw'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Central Florida Real Estate Podcast with Tammie Pickard
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Central
    Florida Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Team Central Florida - your
    professional Central Florida Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Central Florida,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Tammie Pickard
images:
  client_headshot_path: /img/headshot.jpg
  client_headshot_path2: /img/headshot2.jpg
  client_headshot_path3: /img/headshot3.jpg
  client_headshot_path4: /img/headshot4.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#f2cb6b'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 3px
  w_shadow: 5px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'